#!/usr/bin/env python3
"""
make_tiny_model.py - synthesize a small random-weight llama GGUF.

Why this exists: validating a profiler needs a model that runs, not a model
that is good. Downloading a real checkout to test that timestamps land in the
right buckets makes the test suite depend on a network and a few hundred MB,
which means it stops being run.

This writes a structurally valid llama-architecture GGUF with random weights.
Output is gibberish, by construction. It is exactly as useful as a real model
for:

  - checking that scopes nest, that the trace parses, that categories resolve
  - shaking out threading bugs in the instrumentation
  - CI

and exactly as useless for:

  - any claim about how fast real inference is
  - any claim about where time goes in a real model

The generated file records `general.name = "tokenscope-synthetic"` so a trace
taken against it can never be mistaken for a real measurement.

Requires llama.cpp's vendored gguf-py (--llama-cpp points at the checkout) and
numpy.

    python tools/make_tiny_model.py --llama-cpp ../llama.cpp -o models/tiny.gguf
    python tools/make_tiny_model.py --llama-cpp ../llama.cpp -o models/mid.gguf \\
        --layers 16 --embd 512 --heads 8

SPDX-License-Identifier: MIT
"""

from __future__ import annotations

import argparse
import os
import sys

import numpy as np


def build(gguf, out_path: str, *, n_layer: int, n_embd: int, n_head: int,
          n_head_kv: int, n_ff: int, n_vocab: int, n_ctx: int, seed: int) -> None:
    rng = np.random.default_rng(seed)
    head_dim = n_embd // n_head

    w = gguf.GGUFWriter(out_path, "llama")

    w.add_name("tokenscope-synthetic")
    w.add_description(
        "Random weights. Structurally valid, semantically meaningless. "
        "Generated by tokenscope/tools/make_tiny_model.py for profiler testing.")
    w.add_context_length(n_ctx)
    w.add_embedding_length(n_embd)
    w.add_block_count(n_layer)
    w.add_feed_forward_length(n_ff)
    w.add_head_count(n_head)
    w.add_head_count_kv(n_head_kv)
    w.add_rope_dimension_count(head_dim)
    w.add_rope_freq_base(10000.0)
    w.add_layer_norm_rms_eps(1e-5)
    w.add_file_type(gguf.LlamaFileType.ALL_F32)

    # --- a minimal byte-level vocabulary -----------------------------------
    # Real tokenizers are out of scope here; we need ids that round-trip.
    tokens = ["<unk>", "<s>", "</s>"] + [f"<0x{i:02X}>" for i in range(256)]
    tokens += [f"t{i}" for i in range(n_vocab - len(tokens))]
    tokens = tokens[:n_vocab]
    toktypes = [gguf.TokenType.CONTROL if t.startswith("<") else gguf.TokenType.NORMAL
                for t in tokens]

    w.add_tokenizer_model("llama")
    w.add_tokenizer_pre("default")
    w.add_token_list(tokens)
    w.add_token_scores([0.0] * n_vocab)
    w.add_token_types(toktypes)
    w.add_bos_token_id(1)
    w.add_eos_token_id(2)
    w.add_unk_token_id(0)
    w.add_add_bos_token(True)
    w.add_add_eos_token(False)

    # --- weights ------------------------------------------------------------
    # Small magnitudes so activations do not blow up to inf on the way through
    # 16 layers, which would turn a timing test into a NaN hunt.
    def t(*shape) -> np.ndarray:
        return (rng.standard_normal(shape) * 0.02).astype(np.float32)

    def ones(*shape) -> np.ndarray:
        return np.ones(shape, dtype=np.float32)

    n_embd_kv = head_dim * n_head_kv

    w.add_tensor("token_embd.weight", t(n_vocab, n_embd))
    w.add_tensor("output_norm.weight", ones(n_embd))
    w.add_tensor("output.weight", t(n_vocab, n_embd))

    for il in range(n_layer):
        p = f"blk.{il}"
        w.add_tensor(f"{p}.attn_norm.weight", ones(n_embd))
        w.add_tensor(f"{p}.attn_q.weight",    t(n_embd,    n_embd))
        w.add_tensor(f"{p}.attn_k.weight",    t(n_embd_kv, n_embd))
        w.add_tensor(f"{p}.attn_v.weight",    t(n_embd_kv, n_embd))
        w.add_tensor(f"{p}.attn_output.weight", t(n_embd, n_embd))
        w.add_tensor(f"{p}.ffn_norm.weight",  ones(n_embd))
        w.add_tensor(f"{p}.ffn_gate.weight",  t(n_ff,   n_embd))
        w.add_tensor(f"{p}.ffn_up.weight",    t(n_ff,   n_embd))
        w.add_tensor(f"{p}.ffn_down.weight",  t(n_embd, n_ff))

    w.write_header_to_file()
    w.write_kv_data_to_file()
    w.write_tensors_to_file()
    w.close()


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--llama-cpp", default="../llama.cpp",
                    help="llama.cpp checkout, for its vendored gguf-py")
    ap.add_argument("-o", "--out", default="models/tiny.gguf")
    ap.add_argument("--layers", type=int, default=8)
    ap.add_argument("--embd", type=int, default=256)
    ap.add_argument("--heads", type=int, default=8)
    ap.add_argument("--heads-kv", type=int, default=None,
                    help="KV heads (default: same as --heads, i.e. MHA)")
    ap.add_argument("--ff", type=int, default=None, help="default 4x embd")
    ap.add_argument("--vocab", type=int, default=1024)
    ap.add_argument("--ctx", type=int, default=2048)
    ap.add_argument("--seed", type=int, default=1234)
    args = ap.parse_args()

    gguf_py = os.path.abspath(os.path.join(args.llama_cpp, "gguf-py"))
    if not os.path.isdir(gguf_py):
        print(f"error: gguf-py not found at {gguf_py}\n"
              f"       pass --llama-cpp pointing at a llama.cpp checkout",
              file=sys.stderr)
        return 1
    sys.path.insert(0, gguf_py)
    import gguf  # noqa: E402

    if args.embd % args.heads:
        print("error: --embd must be divisible by --heads", file=sys.stderr)
        return 1

    n_head_kv = args.heads_kv or args.heads
    n_ff = args.ff or args.embd * 4

    os.makedirs(os.path.dirname(os.path.abspath(args.out)) or ".", exist_ok=True)
    build(gguf, args.out,
          n_layer=args.layers, n_embd=args.embd, n_head=args.heads,
          n_head_kv=n_head_kv, n_ff=n_ff, n_vocab=args.vocab,
          n_ctx=args.ctx, seed=args.seed)

    mb = os.path.getsize(args.out) / (1 << 20)
    print(f"wrote {args.out}  ({mb:.1f} MB)")
    print(f"  {args.layers} layers, n_embd={args.embd}, "
          f"{args.heads} heads ({n_head_kv} kv), n_ff={n_ff}, vocab={args.vocab}")
    print("  random weights: use for profiler validation, never for perf claims.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
